version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.10

commands:
  save_app_modules:
    steps:
      - save_cache:
          paths:
            - ~/workspace/node_modules
            - ~/workspace/scripts/deploy/node_modules
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".node-version" }}
  restore_app_modules:
    steps:
      - restore_cache:
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".node-version" }}
  save_scripts_modules:
    steps:
      - save_cache:
          paths:
            - ~/workspace/scripts/deploy/node_modules
          key: modules-{{ .Branch }}-{{ checksum "scripts/deploy/yarn.lock" }}-{{ checksum ".node-version" }}
  restore_scripts_modules:
    steps:
      - restore_cache:
          key: modules-{{ .Branch }}-{{ checksum "scripts/deploy/yarn.lock" }}-{{ checksum ".node-version" }}

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_app_modules
      - restore_scripts_modules
      - run:
          name: Install app modules
          command: yarn
      - run:
          name: Install scripts modules
          working_directory: ~/workspace/scripts/deploy
          command: yarn
      - save_app_modules
      - save_scripts_modules
  lint:
    executor: default
    steps:
      - checkout
      - restore_app_modules
      - run:
          name: Lint
          command: yarn lint
  build-test:
    executor: default
    steps:
      - checkout
      - restore_app_modules
      - run:
          name: Build
          command: yarn build
  deploy:
    executor: default
    steps:
      - checkout
      - restore_app_modules
      - deploy:
          command: yarn deploy

workflows:
  process:
    jobs:
      - install:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - lint:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - build-test:
          requires:
            - lint
          filters:
            branches:
              only: /.*/
      - deploy:
          requires:
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
