version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.10

commands:
  save_modules:
    steps:
      - save_cache:
          paths:
            - ~/workspace/node_modules
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".node-version" }}
  restore_modules:
    steps:
      - restore_cache:
          key: modules-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".node-version" }}

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run:
          name: Install
          command: yarn
      - save_modules
  lint:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run:
          name: Lint
          command: yarn lint
  build-test:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run:
          name: Build
          command: yarn build
  deploy:
    executor: default
    steps:
      - checkout
      - restore_modules
      - run:
          name: Deploy
          command: yarn deploy

workflows:
  process:
    jobs:
      - install:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - lint:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - build-test:
          requires:
            - lint
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
      - deploy:
          requires:
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}$/
